
ALTER TABLE document_sets ALTER COLUMN deleted_at TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE document_sets ALTER COLUMN deleted_at TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE documents ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE documents ALTER COLUMN deleted_at TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE sign_results ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE signatures ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.users ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE;